modLoader = "javafml"
loaderVersion = "[41,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/anviaan/anvians-lib/issues"

[[mods]]
modId = "anvianslib"
version = "${version}"
displayName = "Anvian's Lib"
updateJSONURL = "https://api.modrinth.com/updates/PuTjrq4T/forge_updates.json"
displayURL = "https://modrinth.com/mod/anvians-lib"
authors = "anvian"
description = '''
A small utility library for Anvian's mods.
'''
logoFile = "anvianslib.png"

[[dependencies.anvianslib]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.anvianslib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
