plugins {
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false
    id 'net.neoforged.moddev' version '2.0.139' apply false
}

tasks.register("printEnv") {
    doLast {
        def envFile = new File(System.getenv("GITHUB_ENV"))
        envFile.append("MOD_VERSION=${version}\n")
        envFile.append("RELEASE_NAME=${mod_id}-${version}\n")
        envFile.append("GAME_VERSIONS=${minecraft_version_range}\n")
    }
}
