org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.20.6
parchment_mappings_version=2024.06.16
minecraft_version=1.20.6
minecraft_version_range=[1.20.6]
neo_version=20.6.135
neo_version_range=[20.6.135,)
loader_version_range=[1,)


mod_id=anvianslib
mod_name=AnviansLib
mod_license=GPL-3.0
mod_version=1.2.1
mod_group_id=net.anvian.anvianslib
mod_authors=anvian
mod_description=A small utility library for Anvian's mods.
