# Project
version=1.4.1-rc.1
group=net.anvian.anvianslib

# Common
minecraft_version=1.20.1
mod_name=Anvian's Lib
mod_author=anvian
mod_id=anvianslib
license=GPL-3.0
description=A small utility library for Anvian's mods.
minecraft_version_range=[1.20, 1.21)

# Forge
forge_version=47.2.30
forge_loader_version_range=[46,)
forge_version_range=[46,)

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.15.10

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
