plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'org.spongepowered.gradle.vanilla' version '0.2.1-SNAPSHOT'
}
base {
    archivesName = "${mod_id}-common-1.20"
}
minecraft {
    version(minecraft_version)
    if (file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWideners(file("src/main/resources/${mod_id}.accesswidener"))
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
            pom {
                name = "anvian's Lib"
                description = "A small utility library for Anvian's mods."
                url = 'https://github.com/anviaan/anvians-lib/'
                licenses {
                    license {
                        name = 'GNU GPLv3'
                        url = 'https://github.com/anviaan/anvians-lib/blob/main/LICENSE'
                        distribution = 'repo'
                    }
                }
                developers {
                    developer {
                        name = 'anvian'
                    }
                }
            // Remove Minecraft platform deps from the published POM.
            pom.withXml {
                asNode().dependencies.dependency.findAll {
                    it.groupId.text() == 'com.mojang' ||
                    it.groupId.text() == 'net.minecraft'
                }.each { it.parent().remove(it) }
            }
            }
        }
    }
    repositories {
        maven {
            name = "Reposilite"
            url = uri(version.toString().endsWith("SNAPSHOT") ?
                    "https://maven.anvian.net/snapshots" :
                    "https://maven.anvian.net/releases")
            credentials {
                username = (project.findProperty("reposilite.user") as String) ?: System.getenv("REPOSILITE_USER")
                password = (project.findProperty("reposilite.token") as String) ?: System.getenv("REPOSILITE_TOKEN")
            }
        }
    }
}