plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'org.spongepowered.gradle.vanilla'
}
base {
    archivesName = "${mod_id}-common-${minecraft_version}"
}
minecraft {
    version(minecraft_version)
    if (file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWideners(file("src/main/resources/${mod_id}.accesswidener"))
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
            pom {
                name = "anvian's Lib"
                description = "A small utility library for Anvian's mods."
                url = 'https://github.com/anviaan/anvians-lib/'
                licenses {
                    license {
                        name = 'GNU GPLv3'
                        url = 'https://github.com/anviaan/anvians-lib/blob/main/LICENSE'
                        distribution = 'repo'
                    }
                }
                developers {
                    developer {
                        name = 'anvian'
                    }
                }
            }
        }
    }
    repositories {
        maven {
            name = "Repsy"
            url = uri("https://repo.repsy.io/mvn/anvian/anvians-lib")
            credentials {
                username = "anvian"
                password = project.findProperty("gpr.token") ?: System.getenv("REPSY_TOKEN")
            }
        }
    }
}